// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'electronic_invoice_request.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_ElectronicInvoiceRequest _$ElectronicInvoiceRequestFromJson(
  Map<String, dynamic> json,
) => _ElectronicInvoiceRequest(
  operacion: json['operacion'] as String? ?? 'generar_comprobante',
  tipoDeComprobante: (json['tipo_de_comprobante'] as num).toInt(),
  serie: json['serie'] as String,
  numero: json['numero'] as String,
  sunatTransaction: (json['sunat_transaction'] as num?)?.toInt() ?? 1,
  clienteTipoDeDocumento: json['cliente_tipo_de_documento'] as String,
  clienteNumeroDeDocumento: json['cliente_numero_de_documento'] as String,
  clienteDenominacion: json['cliente_denominacion'] as String,
  clienteDireccion: json['cliente_direccion'] as String,
  clienteEmail: json['cliente_email'] as String? ?? '',
  clienteEmail1: json['cliente_email_1'] as String? ?? '',
  clienteEmail2: json['cliente_email_2'] as String? ?? '',
  fechaDeEmision: json['fecha_de_emision'] as String,
  fechaDeVencimiento: json['fecha_de_vencimiento'] as String? ?? '',
  moneda: json['moneda'] as String? ?? '1',
  tipoDeCambio: json['tipo_de_cambio'] as String? ?? '',
  porcentajeDeIgv: json['porcentaje_de_igv'] as String? ?? '18.00',
  descuentoGlobal: json['descuento_global'] as String? ?? '',
  totalDescuento: json['total_descuento'] as String? ?? '',
  totalAnticipo: json['total_anticipo'] as String? ?? '',
  totalGravada: json['total_gravada'] as String,
  totalInafecta: json['total_inafecta'] as String? ?? '',
  totalExonerada: json['total_exonerada'] as String? ?? '',
  totalIgv: json['total_igv'] as String,
  totalGratuita: json['total_gratuita'] as String? ?? '',
  totalOtrosCargos: json['total_otros_cargos'] as String? ?? '',
  total: json['total'] as String,
  percepcionTipo: json['percepcion_tipo'] as String? ?? '',
  percepcionBaseImponible: json['percepcion_base_imponible'] as String? ?? '',
  totalPercepcion: json['total_percepcion'] as String? ?? '',
  totalIncluidoPercepcion: json['total_incluido_percepcion'] as String? ?? '',
  detraccion: json['detraccion'] as String? ?? 'false',
  observaciones: json['observaciones'] as String? ?? '',
  documentoQueSeModificaTipo:
      json['documento_que_se_modifica_tipo'] as String? ?? '',
  documentoQueSeModificaSerie:
      json['documento_que_se_modifica_serie'] as String? ?? '',
  documentoQueSeModificaNumero:
      json['documento_que_se_modifica_numero'] as String? ?? '',
  tipoDeNotaDeCredito: json['tipo_de_nota_de_credito'] as String? ?? '',
  tipoDeNotaDeDebito: json['tipo_de_nota_de_debito'] as String? ?? '',
  enviarAutomaticamenteALaSunat:
      json['enviar_automaticamente_a_la_sunat'] as String? ?? 'true',
  enviarAutomaticamenteAlCliente:
      json['enviar_automaticamente_al_cliente'] as String? ?? 'false',
  codigoUnico: json['codigo_unico'] as String? ?? '',
  condicionesDePago: json['condiciones_de_pago'] as String? ?? '',
  medioDePago: json['medio_de_pago'] as String? ?? '',
  placaVehiculo: json['placa_vehiculo'] as String? ?? '',
  ordenCompraServicio: json['orden_compra_servicio'] as String? ?? '',
  tablaPersonalizadaCodigo: json['tabla_personalizada_codigo'] as String? ?? '',
  formatoDePdf: json['formato_de_pdf'] as String? ?? '',
  items: (json['items'] as List<dynamic>)
      .map((e) => InvoiceItem.fromJson(e as Map<String, dynamic>))
      .toList(),
);

Map<String, dynamic> _$ElectronicInvoiceRequestToJson(
  _ElectronicInvoiceRequest instance,
) => <String, dynamic>{
  'operacion': instance.operacion,
  'tipo_de_comprobante': instance.tipoDeComprobante,
  'serie': instance.serie,
  'numero': instance.numero,
  'sunat_transaction': instance.sunatTransaction,
  'cliente_tipo_de_documento': instance.clienteTipoDeDocumento,
  'cliente_numero_de_documento': instance.clienteNumeroDeDocumento,
  'cliente_denominacion': instance.clienteDenominacion,
  'cliente_direccion': instance.clienteDireccion,
  'cliente_email': instance.clienteEmail,
  'cliente_email_1': instance.clienteEmail1,
  'cliente_email_2': instance.clienteEmail2,
  'fecha_de_emision': instance.fechaDeEmision,
  'fecha_de_vencimiento': instance.fechaDeVencimiento,
  'moneda': instance.moneda,
  'tipo_de_cambio': instance.tipoDeCambio,
  'porcentaje_de_igv': instance.porcentajeDeIgv,
  'descuento_global': instance.descuentoGlobal,
  'total_descuento': instance.totalDescuento,
  'total_anticipo': instance.totalAnticipo,
  'total_gravada': instance.totalGravada,
  'total_inafecta': instance.totalInafecta,
  'total_exonerada': instance.totalExonerada,
  'total_igv': instance.totalIgv,
  'total_gratuita': instance.totalGratuita,
  'total_otros_cargos': instance.totalOtrosCargos,
  'total': instance.total,
  'percepcion_tipo': instance.percepcionTipo,
  'percepcion_base_imponible': instance.percepcionBaseImponible,
  'total_percepcion': instance.totalPercepcion,
  'total_incluido_percepcion': instance.totalIncluidoPercepcion,
  'detraccion': instance.detraccion,
  'observaciones': instance.observaciones,
  'documento_que_se_modifica_tipo': instance.documentoQueSeModificaTipo,
  'documento_que_se_modifica_serie': instance.documentoQueSeModificaSerie,
  'documento_que_se_modifica_numero': instance.documentoQueSeModificaNumero,
  'tipo_de_nota_de_credito': instance.tipoDeNotaDeCredito,
  'tipo_de_nota_de_debito': instance.tipoDeNotaDeDebito,
  'enviar_automaticamente_a_la_sunat': instance.enviarAutomaticamenteALaSunat,
  'enviar_automaticamente_al_cliente': instance.enviarAutomaticamenteAlCliente,
  'codigo_unico': instance.codigoUnico,
  'condiciones_de_pago': instance.condicionesDePago,
  'medio_de_pago': instance.medioDePago,
  'placa_vehiculo': instance.placaVehiculo,
  'orden_compra_servicio': instance.ordenCompraServicio,
  'tabla_personalizada_codigo': instance.tablaPersonalizadaCodigo,
  'formato_de_pdf': instance.formatoDePdf,
  'items': instance.items,
};
